AM.queueDownload("./img/background/background_1.png");
AM.queueDownload("./img/background/background_2.png");
AM.queueDownload("./img/background/background_3.png");
AM.queueDownload("./img/terrain/dirt.jpg");
AM.queueDownload("./img/terrain/red_dirt.jpg");
AM.queueDownload("./img/terrain/purple_dirt.jpg");
AM.queueDownload("./img/explosion/banLeft.png");
AM.queueDownload("./img/explosion/banRight.png");
AM.queueDownload("./img/explosion/banIdle.png");
AM.queueDownload("./img/rocket/projectile1.png");
AM.queueDownload("./img/explosion/explosion.png");
AM.queueDownload("./img/Lime/limeIdle.png");
AM.queueDownload("./img/Lime/limeLeft.png");
AM.queueDownload("./img/Lime/limeRight.png");
AM.queueDownload("./img/Pineapple/pineappleIdle.png");
AM.queueDownload("./img/Pineapple/pineappleLeft.png");
AM.queueDownload("./img/Pineapple/pineappleRight.png");
AM.queueDownload("./img/Coconut/coconutIdle.png");
AM.queueDownload("./img/Coconut/coconutLeft.png");
AM.queueDownload("./img/Coconut/coconutRight.png");
AM.queueDownload("./img/rocket/reticle.png");
AM.queueDownload("./img/hud/hud.png");
AM.queueDownload("./img/weapon/grenadeLauncher.png");
AM.queueDownload("./img/weapon/sniper.png");
AM.queueDownload("./img/weapon/grenadeLauncherB.png");
AM.queueDownload("./img/weapon/sniperB.png");
AM.queueDownload("./img/weapon/airStrike.png");
AM.queueDownload("./img/rocket/sniperBullet.png");
AM.queueDownload("./img/rocket/airRocket.png");

AM.downloadAll(function () {
    var canvas = document.getElementById("gameWorld");
    var ctx = canvas.getContext("2d");
    var gameEngine = new GameEngine();
    gameEngine.init(ctx);
    gameEngine.start();	
	gameEngine.addEntity(new turnManager(gameEngine, ctx));
});